### ISSUE TITLE
linter を ESLint から biome に移行したいかも

### ISSUE THREAD

**Issue by huequica** [huequica/DiscordTrashedDiver#207]
なんと現状の ESLint の flatconfig は各種 editor が対応していないらしく biome に移行するのが実は平たいのではという説が浮上している
https://biomejs.dev/ja/

**Comment by SawadaReverse** [comment]
biome知らんので勉強がてらレビューしたいかも

**Comment by huequica** [comment]
> biome知らんので勉強がてらレビューしたいかも

いいよ。でも単純に移行するだけだから面白くはない可能性あるよ
