### ISSUE TITLE
Node.js バージョンアップ

### ISSUE THREAD

**Issue by SawadaReverse** [huequica/DiscordTrashedDiver#208]
Node.jsの宿命まである
このIssue作成時点のLTSは 20.12.2 らしいんで、そこまで上げたい

package.json にバージョン指定を書くのかとか、.node-version を配置すべきか否かとか議論して、ゴールが定まってからの着手にしたい

**Comment by huequica** [comment]
> package.json にバージョン指定を書くのかとか、.node-version を配置すべきか否かとか議論して、ゴールが定まってからの着手にしたい

まず第一として **`.node-version` ファイルは今後非採用** の立場を取りたい。理由としてはバージョン管理ツールが `nodenv` に限定されるため。それ以外のツールの使用者は全員手動設定を強いられるのは少しつらいところがある。
だったら `package.json` の `engines.node` で node のバージョンを明示してあげたほうがサポート外のバージョンでの動作を抑止できて幸せかもしれない。
