### ISSUE TITLE
`leakMessage` に反応する絵文字を変更する

### ISSUE THREAD

**Issue by huequica** [huequica/DiscordTrashedDiver#32]
`troll_face` だとあまりにも重複しすぎて自分とこの guild の絵文字が見つけづらいことに気づいたので名前だけでも変更

**Comment by SawadaReverse** [comment]
定数として絵文字の名前を定義して、それを使い回すような設定にしたほうが良さそう

**Comment by huequica** [comment]
考えたけど、特定ドメインでしか使用しない知識が config にあるのはちょっと気持ち悪いかなってなったので今まで通りルールに直書きします
