### ISSUE TITLE
replyする時にmentionをオフにする

### ISSUE THREAD

**Issue by chun37** [huequica/DiscordTrashedDiver#38]
鬱陶しいわボケ って感じ

**Comment by huequica** [comment]
`Message#reply` の引数に `ReplyMessageOptions` を受け取るが、これの `allowedMentions.repliedUser` を false にすることで通知を消せる模様
https://scrapbox.io/discordjs-japan/v13%E3%81%AE%E4%B8%BB%E3%81%AA%E5%A4%89%E6%9B%B4%E7%AE%87%E6%89%80
