### ISSUE TITLE
Discordでメッセージが削除されたら、ツイートも削除する

### ISSUE THREAD

**Issue by chun37** [huequica/DiscordTrashedDiver#40]
発言した本人が消したい時に、消せるような仕組みがあったら良さそう

bot が送信したメッセージに、本人がリアクションつけたら削除する みたいな実装だと、かんたんだと思う
message.reference に author があるし、reaction の author があるので

**Comment by huequica** [comment]
- [ ] twitter-api-v2 の消去リクエストするメソッドの interface 調査
	- [ ] `id` のみ受け取る形だとかなり面倒( `/` でslice かけて最後の要素だけ取得してしまうのはアリ)
	- [ ] URL ごと投げられたらいんだけどな(そんなことはないと思うけど)
- [ ] 削除申請絵文字を決める
	- [ ] ❌  が手っ取り早そう？

**Comment by huequica** [comment]
admin と botMaintener も削除可能の対象に入れる

**Comment by huequica** [comment]
予想通り tweetId だけ受け取るらしいのでURLから引き抜く処理が要る
![image](https://user-images.githubusercontent.com/40014236/160234269-09984d94-13f4-4078-bd2e-3a82d1b1eb09.jpeg)

**Comment by huequica** [comment]
reference 元の messageObject は `Message.fetchReference` で取れそう  
https://discord.js.org/#/docs/discord.js/stable/class/Message?scrollTo=fetchReference
![image](https://user-images.githubusercontent.com/40014236/160254145-f266760b-3c6c-4ed8-a5a5-ea12adc01052.png)

**Comment by huequica** [comment]
role まわりは今後の実装としてスキップしたい気持ちが出てきた
